### ISSUE TITLE
Drop shadow

### ISSUE THREAD

**Issue by grahamperrin** [nabendu82/List-all-cookies#1]
The combination of bold + drop shadow is not ideal for legibility/accessibility. 

![2018-08-09 06 12 04 new issue nabendu82-list-all-cookies](https://user-images.githubusercontent.com/192271/43879295-44bf5eea-9b9b-11e8-9dbd-747cd0b5b9ed.png)

Please consider using bold alone. 

Thanks

**Comment by nabendu82** [comment]
Thanks a ton for the reviw. I have fixed the issue and pushed the next version to AMO
<img width="513" alt="screen shot 2018-08-09 at 11 20 33 am" src="https://user-images.githubusercontent.com/17110163/43880529-75a3e2e4-9bc6-11e8-8592-c2601ad1945b.png">
